---
  title: "Covid-19 deaths projections"
  #output: md_document
  output: html_document
---

Get data for UK deaths from World in Data (from )
 
 
Assume some starting point day 0 (say the day that $n$ deaths have occurred).  Let $m_t$ be the number of deaths on day $t = 1,2,..$, $M_t$ the cumulative count, so that $M_t = \sum_{i=1}^t m_i.$

Let $e_t$ the expected number of deaths on day $t$, $E_t$ be the expected total count of deaths after time $t$, so that $E_t = \sum_{i=1}^t e_i.$ .  We assume that $m_t$ is a Poisson random variable with mean $\e_t$, and so  $M_t$ is a Poisson random variable with mean $E_t$, since the sum of independent Poissons is Poisson.

Assume the expected total number of deaths each day increases exponentially, with a daily relative increase of $k$ (so if say $k = 1.3$, the number increases by 30% a day). Then $E_t = kE_{t-1} = k^t E_0$, for some $E_0$.   So $e_t = E_t - E_{t-1} =  k^t E_0 - k^{t-1} E_0 = k^t E_0 (1-1/k).$.  Crucially, this means that
$$ \log e_t = t \log k + \log [E_0 (1-1/k)].$$
A Poisson regression with a $\log$ link function will therefore have a gradient $\log k$.

install.packages("ggplot2")
install.packages("Hmisc")

```{r}
covid.deaths <- read.csv("UK-italy-covid-deaths.csv") # read data into dataframe 

attach(covid.deaths)
date.R = as.Date(date,"%d/%m/%Y")
# calculate oberved counts each day
n=length(UK.deaths)
UK.daily=c(0,diff(UK.deaths))
It.daily=c(0,diff(It.deaths))
UK.daily
days=1:n
ylims=c(1,1500)
plot(date.R,UK.daily,ylim=ylims,type="p", log="y",xlab="Date", ylab = "Daily number of deaths", pch=19,cex=0.9,bty="n",axes=F)
axis.Date(1,at=date.R,cex=0.7)
axis(2,cex=0.7,las=2)
points(date.R,It.daily, pch=1) 
text(date.R[6],20,"Italy")
text(date.R[20],20,"UK")
 

# length of window for fitting

window=10
current.window=(n-window+1) : n  # current UK and It lims
end.It.window = min(which(It.deaths>UK.deaths[n])) # when just exceeds current UK total
It.window = (end.It.window-window+1) : end.It.window

#################
day.weights=rep(1,n) 
day.weights[33]=0.33 # downweight obs on day 33 days ago as only 8 hours deaths
fit.UK.current=glm(UK.daily[current.window] ~ current.window, family="poisson",weights=day.weights[current.window])
summary(fit.UK.current)

coeffs.UK.current=coef(summary(fit.UK.current))
overdisp.UK.current= fit.UK.current$deviance/fit.UK.current$df.residual
se.UK.current=coeffs.UK.current[2,2]*sqrt(overdisp.UK.current)

relative.increase=exp(coeffs.UK.current[2,1])
upper.relative.increase = exp(coeffs.UK.current[2,1]+1.96*se.UK.current )
lower.relative.increase = exp(coeffs.UK.current[2,1]-1.96*se.UK.current )
percent.increase.UK.current=signif(100*(relative.increase-1),2)
upper.percent.increase.UK.current=signif(100*(upper.relative.increase-1),2)
lower.percent.increase.UK.current=signif(100*(lower.relative.increase-1),2)
#################


#################

fit.It.contemp=glm(It.daily[It.window] ~ It.window, family="poisson")
summary(fit.It.contemp)

coeffs.It.contemp=coef(summary(fit.It.contemp))
overdisp.It.contemp= fit.It.contemp$deviance/fit.It.contemp$df.residual
se.It.contemp=coeffs.It.contemp[2,2]*sqrt(overdisp.It.contemp)

relative.increase=exp(coeffs.It.contemp[2,1])
upper.relative.increase = exp(coeffs.It.contemp[2,1]+1.96*se.It.contemp )
lower.relative.increase = exp(coeffs.It.contemp[2,1]-1.96*se.It.contemp )
percent.increase.It.contemp=signif(100*(relative.increase-1),2)
upper.percent.increase.It.contemp=signif(100*(upper.relative.increase-1),2)
lower.percent.increase.It.contemp=signif(100*(lower.relative.increase-1),2)
 #################

# compare gradients

Z= (coeffs.UK.current[2,1]-coeffs.It.contemp[2,1])/sqrt(se.UK.current^2+se.It.contemp^2)
P1= 2*min( pnorm(Z), (1-pnorm(Z) ))

predictions.UK.current=predict( fit.UK.current,  type="link",se.fit=T,dispersion=overdisp.UK.current)  
#predictions.It.current=predict( fit.It.current,  type="link",se.fit=T,dispersion=overdisp.It.current)  
predictions.It.contemp=predict( fit.It.contemp,  type="link",se.fit=T,dispersion=overdisp.It.contemp)  


 
plot(date.R,UK.daily,ylim=ylims,type="p", log="y",xlab="Date", ylab = "Daily number of deaths", pch=19,cex=0.9,bty="n",axes=F)
axis.Date(1,at=date.R,cex=0.7)
axis(2,cex=0.7,las=2)
points(date.R,It.daily, pch=1) 
text(date.R[6],20,"Italy")
text(date.R[20],20,"UK")
lines(date.R[current.window],exp(predictions.UK.current$fit))
#lines(date.R[current.window],exp(predictions.It.current$fit))
lines(date.R[It.window],exp(predictions.It.contemp$fit))

title(paste("Data from World in Data/ECDPC up to March 27th, fitted lines for past", window," days\nUK: Fitted daily increase",percent.increase.UK.current,"%  (95% interval:", lower.percent.increase.UK.current,"% to", upper.percent.increase.UK.current,"%)  \n  It at Uk's stage: Fitted daily increase:",percent.increase.It.contemp,"%  (95% interval:", lower.percent.increase.It.contemp,"% to", upper.percent.increase.It.contemp,"%) \n P=",round(P1,2),"(2-sided, Poisson regression with over-dispersion)"),cex.main=0.8  )

#\n Italy now: Fitted daily increase:",percent.increase.It.current,"%  (95% interval:", lower.percent.increase.It.current,"% to", upper.percent.increase.It.current,"%)
#pdf("UK-italy-deaths-lines-28Mar.pdf")

plot(date.R,UK.daily,ylim=ylims,type="p", log="y",xlab="Date", ylab = "Daily number of deaths", pch=19,cex=0.9,bty="n",axes=F)
axis.Date(1,at=date.R,cex=0.7)
axis(2,cex=0.7,las=2)
points(date.R,It.daily, pch=1) 
text(date.R[6],20,"Italy")
text(date.R[20],20,"UK")
lines(date.R[current.window],exp(predictions.UK.current$fit))
lines(date.R[current.window],exp(predictions.UK.current$fit+1.96*predictions.UK.current$se.fit),lty=2)
lines(date.R[current.window],exp(predictions.UK.current$fit-1.96*predictions.UK.current$se.fit),lty=2)

#lines(date.R[current.window],exp(predictions.It.current$fit))
#lines(date.R[current.window],exp(predictions.It.current$fit+1.96*predictions.It.current$se.fit),lty=2)
#lines(date.R[current.window],exp(predictions.It.current$fit-1.96*predictions.It.current$se.fit),lty=2)

lines(date.R[It.window],exp(predictions.It.contemp$fit))
lines(date.R[It.window],exp(predictions.It.contemp$fit+1.96*predictions.It.contemp$se.fit),lty=2)
lines(date.R[It.window],exp(predictions.It.contemp$fit-1.96*predictions.It.contemp$se.fit),lty=2)
 
      title(paste("Data from World in Data/ECDPC up to March 27th, fitted lines for past", window," days\nUK: Fitted daily increase",percent.increase.UK.current,"%  (95% interval:", lower.percent.increase.UK.current,"% to", upper.percent.increase.UK.current,"%)  \n  It at Uk's stage: Fitted daily increase:",percent.increase.It.contemp,"%  (95% interval:", lower.percent.increase.It.contemp,"% to", upper.percent.increase.It.contemp,"%) \n P=",round(P1,2),"(2-sided, Poisson regression with over-dispersion)"),cex.main=0.8  )

#      \n Italy now: Fitted daily increase:",percent.increase.It.current,"%  (95% interval:", lower.percent.increase.It.current,"% to", upper.percent.increase.It.current,"%)
#dev.off()



fit.It.current=glm(It.daily[current.window] ~ current.window, family="poisson")
summary(fit.It.current)
coeffs.It.current=coef(summary(fit.It.current))
overdisp.It.current= fit.It.current$deviance/fit.It.current$df.residual
se.It.current=coeffs.It.current[2,2]*sqrt(overdisp.It.current)

relative.increase=exp(coeffs.It.current[2,1])
upper.relative.increase = exp(coeffs.It.current[2,1]+1.96*se.It.current )
lower.relative.increase = exp(coeffs.It.current[2,1]-1.96*se.It.current )
percent.increase.It.current=signif(100*(relative.increase-1),2)
upper.percent.increase.It.current=signif(100*(upper.relative.increase-1),2)
lower.percent.increase.It.current=signif(100*(lower.relative.increase-1),2)

########################

# plot loess fit

 

plot(date.R,UK.daily,ylim=ylims,type="p", log="y",xlab="Date", ylab = "Daily number of deaths", pch=19,cex=0.9,bty="n",axes=F)
axis.Date(1,at=date.R,cex=0.7)
axis(2,cex=0.7,las=2)
points(date.R,It.daily, pch=1) 
text(date.R[6],20,"Italy")
text(date.R[20],20,"UK")
   title("Fitted loess line with 95% interval for underlying trajectory")
   
   
It.daily.eps = It.daily+0.0001 # add tiny bit to make log OK (weighting these obs by zero in analysis) 
UK.daily.eps= UK.daily+0.0001   
x=1:n
It.loess= loess( log(It.daily.eps) ~ x ,weights=It.daily.eps,span=1)
pred.It.loess= predict( It.loess, se=T)  

lines(date.R,exp(pred.It.loess$fit ))
lines(date.R,exp(pred.It.loess$fit+1.96*pred.It.loess$se.fit),lty=2)
lines(date.R,exp(pred.It.loess$fit-1.96*pred.It.loess$se.fit),lty=2)

UK.loess= loess( log(UK.daily.eps) ~ x ,weights=UK.daily.eps,span=1)
pred.UK.loess= predict( UK.loess, se=T)  
lines(date.R, exp(pred.UK.loess$fit))
lines(date.R,exp(pred.UK.loess$fit+1.96*pred.UK.loess$se.fit),lty=2)
lines(date.R,exp(pred.UK.loess$fit-1.96*pred.UK.loess$se.fit),lty=2)

# on natural scale
plot(date.R,UK.daily,ylim=ylims,type="p",xlab="Date", ylab = "Daily number of deaths", pch=19,cex=0.9,bty="n",axes=F)
axis.Date(1,at=date.R,cex=0.7)
axis(2,cex=0.7,las=2)
points(date.R,It.daily, pch=1) 
text(date.R[6],20,"Italy")
text(date.R[20],20,"UK")
   title("Fitted loess line with 95% interval for underlying trajectory")

lines(date.R,exp(pred.It.loess$fit ))
lines(date.R,exp(pred.It.loess$fit+1.96*pred.It.loess$se.fit),lty=2)
lines(date.R,exp(pred.It.loess$fit-1.96*pred.It.loess$se.fit),lty=2)

lines(date.R, exp(pred.UK.loess$fit))
lines(date.R,exp(pred.UK.loess$fit+1.96*pred.UK.loess$se.fit),lty=2)
lines(date.R,exp(pred.UK.loess$fit-1.96*pred.UK.loess$se.fit),lty=2)


```

p <- ggplot() 
p <- p + geom_point(covid.deaths , mapping=aes(x=days, y=UK.daily), size=3.5,col=1) # defines 
p <- p + geom_point(covid.deaths , mapping=aes(x=days, y=It.daily), size=3.5,col=2) 

p <- p + expand_limits(x = c(min.day,max.day),y=c(0,500))
p <- p + scale_y_continuous(trans='log10')
p <- p +  labs(x="Day (starting Feb 23)", y = "Daily number of deaths", title="UK and Italy")  

p

fit=glm(UK.daily ~ days, family="poisson",data=covid.deaths)
summary(fit)

predictions=predict(fit, data.frame(days), type="response")  # predictions for extreme cases
pred.int=predict(fit, data.frame(days), type="response",interval="prediction", level=0.95)
coeffs= coef(summary(fit))
relative.increase=exp(coeffs[2,1])
upper.relative.increase = exp(coeffs[2,1]+1.96*coeffs[2,2] )
lower.relative.increase = exp(coeffs[2,1]-1.96*coeffs[2,2] )
percent.increase=signif(100*(relative.increase-1),2)
upper.percent.increase=signif(100*(upper.relative.increase-1),2)
lower.percent.increase=signif(100*(lower.relative.increase-1),2)

pred.frame = data.frame(Extremes=min.day:max.day,predictions ) # data frame for predictions

p <- ggplot() 
p <- p + geom_point(covid.deaths , mapping=aes(x=days, y=UK.daily), size=3.5,col=1) # defines 
p <- p + expand_limits(x = c(1,max.day),y=c(0,500))
p <- p + scale_y_continuous(trans='log10')
#p <- p +  labs(x="Day (starting Feb 23)", y = "Daily number of deaths", title="UK and Italy")  

p <- p +  labs(x="Day (starting Feb 23)", y = "Daily number of deaths", title=paste("UK: Fitted daily increase:",percent.increase,"%  (95% interval:", lower.percent.increase,"% to", upper.percent.increase,"%)"))   
p <- p + geom_line(dat=pred.frame, aes(x=Extremes,y=predictions), size=1) # add previously fitted Poisson regression line  

p
```

 


 